apiVersion: v1
kind: Service
metadata:
  name: ysjcache01
spec:
  ports:
  - port: 11211
#    nodePort: 11201
    targetPort: ysjmc-port
    protocol: TCP
  selector:
    app: ysjmc 
  type: NodePort
