apiVersion: v1
kind: Pod
metadata:
  name: ysjdb
  labels:
    app: ysjdb
spec:
  containers:
  - name: ysjdb
    image: visualpath/ysjmultidb
    ports:
    - name: ysjdb-port
      containerPort: 3306

    env:
     - name: MYSQL_ROOT_PASSWORD
       value: "ysjdbpass"

