apiVersion: v1
kind: Service
metadata:
  name: ysjapp-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: ysjapp-port
    protocol: TCP
  selector:
    app: ysjapp
  type: NodePort
