apiVersion: apps/v1
kind: Deployment
metadata:
  name: ysjapp-deployment
  labels:
    app: ysjapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ysjapp
  template:
    metadata:
      labels:
        app: ysjapp
    spec:
      containers:
      - name: ysjapp
        image: visualpath/ysjmultiapp
        ports:
        - name: ysjapp-port
          containerPort: 8080
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: ysjapp-service
spec:
  ports:
  - port: 80
#    nodePort: 31001
    targetPort: ysjapp-port
    protocol: TCP
  selector:
    app: ysjapp
  type: LoadBalancer

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-amine-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: ysjapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
